apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator-prod
  namespace: argocd
  labels:
    cluster: prod
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    targetRevision: 1.14.1
    path: manifests/charts/istio-operator/
  destination:
    server: https://api.devops-prod.keerthigpi.shoot.canary.k8s-hana.ondemand.com
    namespace: istio-operator
