apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack-crds-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    cluster: dev
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-34.1.1
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
