apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    cluster: dev
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 34.1.1
    helm:
      skipCrds: true
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
