apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    cluster: prod
spec:
  destination:
    server: https://api.devops-prod.keerthigpi.shoot.canary.k8s-hana.ondemand.com
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 34.1.1
    helm:
      skipCrds: true
    chart: kube-prometheus-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
