apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prom-stack-crds-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    cluster: prod
spec:
  destination:
    server: https://api.devops-prod.keerthigpi.shoot.canary.k8s-hana.ondemand.com
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-34.1.1
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
