apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.tools.sap/I526709/DevOps-assignment
  password: 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 #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
  username: I526709